services:
  - type: web
    name: plagiarism-detector-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: IEEE_XPLORE_API_KEY
        sync: false
